---
title: "Data exploration"
author: "Justin, Ian, Travis"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(ggplot2)
library(dplyr)
library(tidyr)
library(lubridate)
```


```{r}
data_8 <- read_excel("referencetable06072022accessible.xlsx", 
                   sheet = "Table 8",
                   skip = 3)
```


```{r}
#rename columns to not have spaces between them; easier to work with
data_8 <- data_8 %>% rename(Cause_of_death = `Cause of Death`, Age_group = `Age group`, Status = `Vaccination status`, Deaths = `Count of Deaths`)
data_8$Deaths <- data_8$Deaths %>% as.numeric() #set to numeric
data_8 <- data_8 %>%  filter(!is.na(Deaths)) #remove NAs
data_8$Status <- as.factor(data_8$Status)
data_8$Age_group <- as.factor(data_8$Age_group)
head(data_8)
```

```{r}
hist(data_8$Deaths)
```





```{r}
data_8 %>% filter(Year == 2022) %>% group_by(Status) %>% 
  ggplot(aes(x = Month, y = Deaths, color = Status))+
  geom_col()
```


```{r}
#data_8$Month <-  match(data_8$Month, month.name)
#changing months to integers
```



```{r}
data_1 <- read_excel("referencetable06072022accessible.xlsx", 
                   sheet = "Table 1",
                   skip=3)

```

```{r}
data_1 <- data_1 %>% rename(Cause_of_death = `Cause of Death`, Status = `Vaccination status`, Deaths = `Count of deaths`)
data_1$Deaths <- data_1$Deaths %>% as.numeric() #set to numeric
data_1 <- data_1 %>%  filter(!is.na(Deaths)) #remove NAs
data_1$Status <- as.factor(data_1$Status)
data_1$Cause_of_death <- as.factor(data_1$Cause_of_death)
head(data_1)
```


```{r}
data_1 %>% filter(Year == 2022,Status == 'Unvaccinated' | Status == 'Ever vaccinated',Cause_of_death == 'All causes') %>% mutate(DeathsPerPersonYrs = Deaths/`Person-years`)
```



```{r}
data_1 %>% filter(Year == 2022,Status == 'Unvaccinated' | Status == 'Ever vaccinated',Cause_of_death == 'All causes') %>% mutate(DeathsPerPersonYrs = Deaths/`Person-years`) %>% 
  ggplot(aes(x = Month, y = DeathsPerPersonYrs, color=Status))+
  geom_col()
```














